export const dropDownOptions={
   relevance : ["Select Relevance", "1", "2", "3", "4", "5", "6", "7"],
   likelihood : ["Select Likelihood", "1", "2", "3", "4"],
   intensity : ["Select Intensity", "1", "2", "3", "4", "6", "8", "9", "10", "12", "14", "15", "16", "18", "20", "24", "30", "32", "36", "40", "48", "60", "72", "96"],
   start_year : ["Select Startyear", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2025", "2028", "2030", "2035", "2040", "2050"],
   end_year : ["Select Endyear", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2024", "2025", "2026", "2027", "2028", "2030", "2034", "2035", "2036", "2040", "2041", "2046", "2050", "2051", "2055", "2060", "2126", "2200"],
   country : ["Select Country", "Algeria", "Angola", "Argentina", "Australia", "Austria", "Azerbaijan", "Belize", "Brazil", "Burkina Faso", "Canada", "China", "Colombia", "Cyprus", "Denmark", "Egypt", "Estonia", "Ethiopia", "Gabon", "Germany", "Ghana", "Greece", "Hungary", "India", "Indonesia", "Iran", "Iraq", "Japan", "Jordan", "Kazakhstan", "Kuwait", "Lebanon", "Liberia", "Libya", "Malaysia", "Mali", "Mexico", "Morocco", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Poland", "Qatar", "Russia", "Saudi Arabia", "South Africa", "South Sudan", "Spain", "Syria", "Turkey", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Venezuela"],
   region : ["Select Region", "Africa", "Asia", "Central Africa", "Central America", "Central Asia", "Eastern Africa", "Eastern Asia", "Eastern Europe", "Europe", "Northern Africa", "Northern America", "Northern Europe", "Oceania", "South America", "South-Eastern Asia", "Southern Africa", "Southern Asia", "Southern Europe", "Western Africa", "Western Asia", "Western Europe", "World", "world"],
   sector : ["Select Sector", "Aerospace & defence", "Automotive", "Construction", "Energy", "Environment", "Financial services", "Food & agriculture", "Government", "Healthcare", "Information Technology", "Manufacturing", "Media & entertainment", "Retail", "Security", "Support services", "Tourism & hospitality", "Transport", "Water"],
   topic : ['Select Topic', "3D", "Washington", "administration", "agriculture", "aquaculture", "artificial intelligence", "asylum", "automaker", "bank", "battery", "biofuel", "brexit", "building", "business", "capital", "car", "carbon", "change", "city", "climate", "climate change", "clothing", "coal", "communication", "consumer", "consumption", "crisis", "data", "debt", "demand", "economic", "economic growth", "economy", "election", "electricity", "emission", "energy", "export", "factory", "farm", "finance", "food", "fossil fuel", "fracking", "gamification", "gas", "gasoline", "gdp", "government", "greenhouse gas", "growth", "ice", "industry", "inflation", "information", "infrastructure", "interest rate", "investment", "market", "material", "money", "nuclear", "oil", "peak oil", "plastic", "policy", "politics", "pollution", "population", "power", "production", "resource", "revenue", "risk", "robot", "security", "shale gas", "shortage", "software", "storm", "strategy", "tax", "technology", "tension", "terrorism", "tourist", "trade", "transport", "transportation", "unemployment", "vehicle", "war", "water", "wealth", "work", "worker", "workforce"],
}